namespace: pulsar-preprod

#images:
#  zookeeper:
#    tag: 2.6.0
#  bookie:
#    tag: 2.6.0
#  presto:
#    tag: 2.6.0
#  autorecovery:
#    tag: 2.6.0
#  broker:
#    tag: 2.6.0
#  proxy:
#    tag: 2.6.0
#  pulsar_detector:
#    tag: 2.6.0
#  functions:
#    tag: 2.6.0
##  prometheus:
##    tag: v2.21.0

zookeeper:
  resources:
    limits:
      memory: 384Mi
      cpu: 125m
    requests:
      memory: 384Mi
      cpu: 125m
  volumes:
    data:
      size: 5Gi
    dataLog:
      size: 1Gi
  configData:
    PULSAR_MEM: >
      -Xms192m -Xmx384m

bookkeeper:
  metadata:
    resources:
      limits:
        cpu: 250m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 2Gi
  resources:
    limits:
      cpu: 250m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 2Gi
  volumes:
    journal:
      size: 5Gi
    ledgers:
      size: 15Gi
  configData:
    # `BOOKIE_MEM` is used for `bookie shell`
    BOOKIE_MEM: >
      -Xms512m
      -Xmx1g
      -XX:MaxDirectMemorySize=1g
    # we use `bin/pulsar` for starting bookie daemons
    PULSAR_MEM: >
      -Xms1g
      -Xmx2g
      -XX:MaxDirectMemorySize=2g

autorecovery:
  resources:
    limits:
      cpu: 125m
      memory: 384Mi
    requests:
      cpu: 125m
      memory: 384Mi
  configData:
    BOOKIE_MEM: >
      -Xms128m -Xmx256m

#pulsar_metadata:
#  image:
#    tag: 2.6.0

broker:
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  configData:
    PULSAR_MEM: >
      -Xms512m -Xmx1g -XX:MaxDirectMemorySize=1g

proxy:
  resources:
    limits:
      cpu: 125m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 512Mi
  configData:
    PULSAR_MEM: >
      -Xms256m -Xmx512m -XX:MaxDirectMemorySize=512m

#toolset:
#  resources:
#    limits:
#      memory: 256Mi
#      cpu: 0.1
#    requests:
#      memory: 256Mi
#      cpu: 0.1

prometheus:
  resources:
    limits:
      memory: 768Mi
      cpu: 250m
    requests:
      memory: 768Mi
      cpu: 250m
#  volumes:
#    data:
#      size: 10Gi

grafana:
  #    limits:
  #      memory: 250Mi
  #      cpu: 0.1
  #    requests:
  #      memory: 250Mi
  #      cpu
#  reso: 0.1
  env:
    GF_SERVER_ROOT_URL: "https://pulsar-grafana-preprod.singlespot.com"
#  persistence:
#    size: 1Gi
#  sidecar:
#    resources:
#      limits:
#        cpu: 100m
#        memory: 100Mi
#      requests:
#        cpu: 100m
#        memory: 100Mi

pulsar_manager:
#  resources:
#    limits:
#      memory: 250Mi
#      cpu: 0.1
#    requests:
#      memory: 250Mi
#      cpu: 0.1
  redirect:
    host: pulsar-manager-preprod.singlespot.com
#  volumes:
#    data:
#      size: 1Gi

#presto:
#  coordinator:
#    resources:
#      limits:
#        memory: 4Gi
#        cpu: 2
#      requests:
#        memory: 4Gi
#        cpu: 2
#  worker:
#    resources:
#      limits:
#        memory: 4Gi
#        cpu: 2
#      requests:
#        memory: 4Gi
#        cpu: 2

prometheusJobs:
  - jobName: copy-api
    host: pulsar-copy-metrics-preprod.singlespot.com
  - jobName: geocoding-api
    host: geocoding-api-metrics-preprod.singlespot.com
  - jobName: producer-api
    host: pulsar-producer-metrics-preprod.singlespot.com

servicesNamespace: pulsar-services-preprod
