namespace: pulsar-preprod

#images:
#  zookeeper:
#    tag: 2.6.0
#  bookie:
#    tag: 2.6.0
#  presto:
#    tag: 2.6.0
#  autorecovery:
#    tag: 2.6.0
#  broker:
#    tag: 2.6.0
#  proxy:
#    tag: 2.6.0
#  pulsar_detector:
#    tag: 2.6.0
#  functions:
#    tag: 2.6.0
##  prometheus:
##    tag: v2.21.0

#zookeeper:
#  resources:
#    limits:
#      memory: 256Mi
#      cpu: 0.1
#    requests:
#      memory: 256Mi
#      cpu: 0.1
#  volumes:
#    data:
#      size: 5Gi
#    dataLog:
#      size: 1Gi

#bookkeeper:
#  metadata:
#    image:
#      tag: 2.6.0
#  resources:
#    limits:
#      memory: 512Mi
#      cpu: 0.2
#    requests:
#      memory: 512Mi
#      cpu: 0.2
#  volumes:
#    journal:
#      size: 5Gi
#    ledgers:
#      size: 15Gi

#autorecovery:
#  resources:
#    limits:
#      memory: 128Mi
#      cpu: 0.1
#    requests:
#      memory: 128Mi
#      cpu: 0.1

#pulsar_metadata:
#  image:
#    tag: 2.6.0

#broker:
#  resources:
#    limits:
#      memory: 512Mi
#      cpu: 0.2
#    requests:
#      memory: 512Mi
#      cpu: 0.2

#proxy:
#  resources:
#    limits:
#      memory: 128Mi
#      cpu: 0.2
#    requests:
#      memory: 128Mi
#      cpu: 0.2

#toolset:
#  resources:
#    limits:
#      memory: 256Mi
#      cpu: 0.1
#    requests:
#      memory: 256Mi
#      cpu: 0.1

#prometheus:
#  resources:
#    limits:
#      memory: 256Mi
#      cpu: 0.1
#    requests:
#      memory: 256Mi
#      cpu: 0.1
#  volumes:
#    data:
#      size: 10Gi

grafana:
  #    limits:
  #      memory: 250Mi
  #      cpu: 0.1
  #    requests:
  #      memory: 250Mi
  #      cpu
#  reso: 0.1
  env:
    GF_SERVER_ROOT_URL: "https://pulsar-grafana-preprod.singlespot.com"
#  persistence:
#    size: 1Gi
#  sidecar:
#    resources:
#      limits:
#        cpu: 100m
#        memory: 100Mi
#      requests:
#        cpu: 100m
#        memory: 100Mi

pulsar_manager:
#  resources:
#    limits:
#      memory: 250Mi
#      cpu: 0.1
#    requests:
#      memory: 250Mi
#      cpu: 0.1
  redirect:
    host: pulsar-manager-preprod.singlespot.com
#  volumes:
#    data:
#      size: 1Gi

#presto:
#  coordinator:
#    resources:
#      limits:
#        memory: 4Gi
#        cpu: 2
#      requests:
#        memory: 4Gi
#        cpu: 2
#  worker:
#    resources:
#      limits:
#        memory: 4Gi
#        cpu: 2
#      requests:
#        memory: 4Gi
#        cpu: 2

prometheusJobs:
  - jobName: copy-api
    host: pulsar-copy-metrics-preprod.singlespot.com
  - jobName: geocoding-api
    host: geocoding-api-metrics-preprod.singlespot.com
  - jobName: producer-api
    host: pulsar-producer-metrics-preprod.singlespot.com

servicesNamespace: pulsar-services-preprod
