#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.monitoring.grafana }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.grafana.component }}-datasources"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.grafana.component }}
    grafana_datasource: "1"
data:
  datasource.yml: |
    # config file version
    apiVersion: 1

    # list of datasources to insert/update depending
    # on what's available in the database
    datasources:
      # <string, required> name of the datasource. Required
      - name: "Prometheus"
        # <string, required> datasource type. Required
        type: prometheus
        # <string, required> access mode. direct or proxy. Required
        access: proxy
        # <int> org id. will default to orgId 1 if not specified
        orgId: 1
        # <string> url
        url: "http://{{ template "pulsar.fullname" . }}-{{ .Values.prometheus.component }}:9090/{{ template "pulsar.control_center_path.prometheus" . }}"
        # <string> database password, if used
        # password:
        # <string> database user, if used
        # user:
        # <string> database name, if used
        # database:
        # <bool> enable/disable basic auth
        basicAuth: false
        # <string> basic auth username
        # basicAuthUser:
        # <string> basic auth password
        # basicAuthPassword:
        # <bool> enable/disable with credentials headers
        # withCredentials:
        # <bool> mark as default datasource. Max one per org
        # isDefault:
        # <map> fields that will be converted to json and stored in json_data
        # jsonData:
        #    graphiteVersion: "1.1"
        #    tlsAuth: false
        #    tlsAuthWithCACert: false
        #    httpHeaderName1: "Authorization"
        # <string> json object of data that will be encrypted.
        # secureJsonData:
        #   tlsCACert: "..."
        #   tlsClientCert: "..."
        #   tlsClientKey: "..."
        #   # <openshift\kubernetes token example>
        #   httpHeaderValue1: "Bearer xf5yhfkpsnmgo"
        version: 1
        # <bool> allow users to edit datasources from the UI.
        editable: true
      - name: "Loki"
        type: loki
        access: proxy
        url: "http://{{ .Release.Name }}-loki.{{ .Release.Namespace }}.svc.cluster.local:3100/"
        version: 1
        editable: true
{{- end }}
