{
 "title": "Copy API",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Percentage of 2xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{exported_job=\"data_stream_copy_gunicorn_response_code\", status=~\"2..\"}) / sum(data_stream_copy_gunicorn_requests) * 100",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Percentage of 3xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{exported_job=\"data_stream_copy_gunicorn_response_code\", status=~\"3..\"}) / sum(data_stream_copy_gunicorn_requests) * 100",
     "legendFormat": "3XX"
    }
   ]
  },
  {
   "title": "Percentage of 4xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{exported_job=\"data_stream_copy_gunicorn_response_code\", status=~\"4..\"}) / sum(data_stream_copy_gunicorn_requests) * 100",
     "legendFormat": "4XX"
    }
   ]
  },
  {
   "title": "Percentage of 5xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_code{exported_job=\"data_stream_copy_gunicorn_response_code\", status=~\"5..\"}) / sum(data_stream_copy_gunicorn_requests) * 100",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(data_stream_copy_gunicorn_requests[1m])"
    }
   ]
  },
  {
   "title": "Logged critical",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "data_stream_copy_gunicorn_log_critical"
    }
   ]
  },
  {
   "title": "Logged errors (including exceptions)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(data_stream_copy_gunicorn_log_exception or vector(0)) + sum(data_stream_copy_gunicorn_log_error or vector(0))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "data_stream_copy_gunicorn_request_duration_sum / data_stream_copy_gunicorn_request_duration_count"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "data_stream_copy_gunicorn_request_duration{quantile=\"0.5\"}",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "data_stream_copy_gunicorn_request_duration{quantile=\"0.9\"}",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "data_stream_copy_gunicorn_request_duration{quantile=\"0.99\"}",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}